### ISSUE TITLE
Can I show my PPT in  a winform?

### ISSUE THREAD

**Issue by weituotian** [solegaonkar/Play-With-PPT#1]
is it possible?

**Comment by solegaonkar** [comment]
I am sorry for delay in response.. Actually this project is more than an year old. Don't remember much about it :( 
If I am not demanding too much, can you please try it and update it on this comment? I am badly tied down in my work right now.
Sorry for letting you down!

**Comment by solegaonkar** [comment]
Hi Weituotial

I am sorry for delay in response.. Actually this project is more than an year old. Don't remember much about it :(
If I am not demanding too much, can you please try it and update it on this comment? I am badly tied down in my work right now.
Sorry for letting you down!

**Comment by solegaonkar** [comment]
.
